[package]
name = "comrak"
version = "0.2.8"
authors = ["Ashe Connor <kivikakk@github.com>"]
description = "A 100% CommonMark-compatible GitHub Flavored Markdown parser and formatter"
documentation = "https://docs.rs/comrak"
homepage = "https://github.com/kivikakk/comrak"
repository = "https://github.com/kivikakk/comrak"
readme = "README.md"
keywords = ["markdown", "commonmark"]
license = "BSD-2-Clause"
categories = ["text-processing", "parsing", "command-line-utilities"]

[badges]
travis-ci = { repository = "kivikakk/comrak" }

[profile.release]
lto = true

[[bin]]
name = "comrak"
required-features = ["clap"]
doc = false

[dependencies]
typed-arena = "1.3"
regex = "0.2"
lazy_static = "1.0"
entities = "1.0"
unicode_categories = "0.1"
clap = { version = "2.29", optional = true }
twoway = "0.1"
pest = { git = "https://github.com/dragostis/pest", branch = "v1.1" }
pest_derive = { git = "https://github.com/dragostis/pest", branch = "v1.1" }

[features]
default = ["clap"]
benchmarks = []
